### ISSUE TITLE
GraphqlError: ["Pull request Pull request is in unstable status"]

### ISSUE THREAD

**Issue by izavads** [daneden/enable-automerge-action#120]
Hi,
getting the below when trying to use the action : 

```

(node:202334) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'enablePullRequestAutoMerge' of undefined
    at main (/home/i/preProdCi/runner1/_work/_actions/daneden/enable-automerge-action/v1/dist/index.js:4632:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:202334) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:202334) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: GraphqlError: ["Pull request Pull request is in unstable status"]
```

**Comment by Nick2bad4u** [comment]
Getting a similar error:

```
Run daneden/enable-automerge-action@v1
  with:
    github-token: ***
    allowed-author: dependabot[bot]
    merge-method: MERGE
Error: GraphqlError: Pull request Pull request is in unstable status
D:\a\_actions\daneden\enable-automerge-action\v1\dist\index.js:463[2](https://github.com/Nick2bad4u/BHBot/actions/runs/8762233730/job/24049731912#step:2:2)
  } = data;
      ^

TypeError: Cannot read properties of undefined (reading 'enablePullRequestAutoMerge')
    at main (D:\a\_actions\daneden\enable-automerge-action\v1\dist\index.js:46[3](https://github.com/Nick2bad4u/BHBot/actions/runs/8762233730/job/24049731912#step:2:3)2:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:[5](https://github.com/Nick2bad4u/BHBot/actions/runs/8762233730/job/24049731912#step:2:5))
```
